@startuml FastDelivery_DiagramaClasses

class Cliente {
  
}

class Restaurante {
  
}

class Pedido {
  
  
}

class Entregador {
  
}

class Pagamento {
  
}

' Relacionamentos
Cliente  --  Pedido
Restaurante  --  Pedido
Pedido  --  Item
Pedido  --  Pagamento
Pedido  --  Entregador
Restaurante  --  Item

@enduml